//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcGuitarists.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GuitaristTable
    {
        public int Id { get; set; }

        [Display(Name = "Profile Image")]
        public string Image { get; set; }

        [Required, StringLength(60, MinimumLength = 3)]
        public string Name { get; set; }

        [Required, StringLength(60)]
        public string Roles { get; set; }

        [Display(Name = "Member Of"), StringLength(60, MinimumLength = 3)]
        public string MemberOf { get; set; }

        [Required, RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$"), StringLength(60)]
        public string Genre { get; set; }
    }
}
